### ISSUE TITLE
Are you sharing the SQL dump?

### ISSUE THREAD

**Issue by jcfrane** [bkintanar/psgc-api#14]
Hi, I am using your API last weekend, however, it produces errors now. 

I am planning to deploy it on my own server myself, can I ask for the actual SQL Dump?

Thank you very much!

**Comment by jcfrane** [comment]
NVM, found the data in storage folder. 

Thank you very much for providing this repo.

**Comment by bkintanar** [comment]
@jcfrane I'm glad that you've figured it out. Care to share the error so that I can check and fix it?

**Comment by jcfrane** [comment]
@bkintanar it's weird, your public API is working now. 

Do you mind if provide Dockerfile in your repository?

**Comment by bkintanar** [comment]
@jcfrane PR is always welcome! :)

**Comment by bkintanar** [comment]
@jcfrane you can also check https://github.com/bkintanar/psgc-api-wrapper if you're using Laravel / PHP
