### ISSUE TITLE
REGION 13 Missing?

### ISSUE THREAD

**Issue by jcfrane** [bkintanar/psgc-api#15]
Hi, Region 13 (CARAGA) is missing... why is that so?

Thanks!

**Comment by bkintanar** [comment]
@jcfrane it's in page 2. You can either add a ?per_page=20 query parameter (default items per page is set to 15), or you can directly access page 2 by ?page=2.

http://bkintanar.site/api/regions?per_page=20
http://bkintanar.site/api/regions?page=2

**Comment by jcfrane** [comment]
> @jcfrane it's in page 2. You can either add a ?per_page=20 query parameter (default items per page is set to 15), or you can directly access page 2 by ?page=2.
> 
> http://bkintanar.site/api/regions?per_page=20
> http://bkintanar.site/api/regions?page=2

Yeah, just realized id right after I filed an issue hehehehe.
