### ISSUE TITLE
How can I get PATEROS?

### ISSUE THREAD

**Issue by jcfrane** [bkintanar/psgc-api#16]
Is there a way for me to get PATEROS?

thanks!

**Comment by bkintanar** [comment]
@jcfrane how do you mean?

**Comment by jcfrane** [comment]
@bkintanar PATEROS doesn't appear on NCR, DISTRICT 4 or is it a municipality?

**Comment by bkintanar** [comment]
You are right, it seems that PATEROS is the only municipality in NCR. The database needs some modifications to cater this. I'll leave this issue open for now, I might have time to work on this during the weekend.

Thanks for reporting.

**Comment by jcfrane** [comment]
@bkintanar it's on SARANGGANI now.

**Comment by bkintanar** [comment]
Yes. Which is wrong. I'll make time to fix it this weekend.

**Comment by bkintanar** [comment]
@jcfrane looks like weekend came early for you. Kindly test.

![image](https://user-images.githubusercontent.com/685928/98651968-ebd9d700-2375-11eb-933e-96176ac88bae.png)

![image](https://user-images.githubusercontent.com/685928/98651877-c77dfa80-2375-11eb-9e25-b9917620f191.png)

**Comment by jcfrane** [comment]
Wow Thanks!

**Comment by jcfrane** [comment]
Will let you know once i tested it.

**Comment by jcfrane** [comment]
Tested working! Very much thanks!
