### ISSUE TITLE
Error in `api/barangays`

### ISSUE THREAD

**Issue by baynte** [bkintanar/psgc-api#17]

**Comment by clrke** [comment]
+1

**Comment by arnold-plxr** [comment]
Experiencing the same issue :)

<img width="1251" alt="postman" src="https://user-images.githubusercontent.com/63797953/105932390-c3659d00-6087-11eb-876f-dab6eed1a9ec.png">

**Comment by C0D37355** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/40661558/106171578-a71f4880-61cc-11eb-81c3-29fbc3eebbd8.png)

**Comment by bkintanar** [comment]
Thank you all. Check ko mamaya.

**Comment by bkintanar** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/685928/106230086-b385be80-6229-11eb-8a75-79c614a05f63.png)

**Comment by arnold-plxr** [comment]
Its working now! Thank you @bkintanar  🚀

**Comment by bkintanar** [comment]
Thanks master @arnold-plxr !
