### ISSUE TITLE
Database Seeder not working.

### ISSUE THREAD

**Issue by rodelm17** [bkintanar/psgc-api#19]
no database seeder found.

**Comment by bkintanar** [comment]
@rmangulabnan yes this is correct. There are no seeders in place. Because the data used comes from an Excel file that PSGC supplies.

**Comment by rmangulabnan** [comment]
can i have the latest database if possible?

**Comment by rmangulabnan** [comment]
please email me the complete database to my email rodelmangulabnan@yopmail.com

**Comment by rodelm17** [comment]
please provide database

**Comment by bkintanar** [comment]
Just pull in the latest code, then run the console command `php artisan psgc:parse`. It should load up the db.

**Comment by rodelm17** [comment]
thank you
